### ISSUE TITLE
Switch out disqus for commento?

### ISSUE THREAD

**Issue by Tuxified** [kabisa/theguild.nl#100]
Personally I have disqus disabled for privacy reasons, sounds like commento is a better alternative (especially since it's open source): https://commento.io/

**Comment by VincentTam** [comment]
However, it's not free as in free beer.  What about [Staticman](https://staticman.net)?  It makes use of GitHub/GitLab Pull/Merge Requests to render comments as static content of a site.

P.S. I maintain @staticmanlab, a public GitLab instance of Staicman. Staticman  instead of issues.

**Comment by thnukid** [comment]
There are many ways to Rome, another one would be https://jamstack-comments.netlify.com/about/ - uses netlify forms + slack.

I will take a look at Staticman.

**Comment by VincentTam** [comment]
Jamstack :+1:
