### ISSUE TITLE
Enforce connection between Kabisa and The Guild

### ISSUE THREAD

**Issue by bazzel** [kabisa/theguild.nl#31]
There is no link to the tech blog from the current Kabisa site. There is only one small link to Kabisa from the tech blog.

See also: https://github.com/kabisa/kabisa.nl/issues/98

**Comment by thnukid** [comment]
> There is no link to the tech blog from the current Kabisa site.

kabisa/kabisa.nl#98 has been resolved with kabisa/kabisa.nl#261 - Closing this issue 📦
