### ISSUE TITLE
Gracefully deal with slow loading images

### ISSUE THREAD

**Issue by bazzel** [kabisa/theguild.nl#37]
Suggestions:
- Some kind of nice transitioning effect after image loads (and sane placeholder styles until it does)
- Using a small version of a header image (e.g. 80-byte base64 inine image) until full version loaded, to create a color-faded low res placeholder
- Progessive JPG

**Comment by RoelN** [comment]
Before we get to a technical computer science solution, the two most recent posts with header images have 500KB and 1.1MB images. We should give warnings when huge files are being used, and make it easier to optimise those.

That said, a preview image would be nice. I like the inline idea. We could combine an ImageOptim-styled optimisation in the build process with something that poops out 80 byte images, and adds the base64 version as text content to the (Contentful?) data.

Who wants to pick this up with me?

**Comment by Tuxified** [comment]
@RoelN pick me, pick me :raised_hands:

**Comment by thnukid** [comment]
@RoelN  [middleman-async-image](https://github.com/bastienrobert/middleman-async-image) might do what we need.
