### ISSUE TITLE
Layout squeezed on iPhone

### ISSUE THREAD

**Issue by pascalw** [kabisa/theguild.nl#77]
![image](https://cloud.githubusercontent.com/assets/304603/14361652/333568bc-fcfc-11e5-879e-7f0d0584c49b.png)

Likely due to the long word 'therubyracer' not breaking up. @RoelN any other solution than to add some break-word css?

**Comment by RoelN** [comment]
Same problem as the Kabisa site: the type is too large. This sucks, I know :( Quick fix would be to have a much smaller font size for mobile. Someone can take a stab at that, or I can next week.
